services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - node_modules
            - app
        - action: rebuild
          path: ./package.json
          target: /app/package.json

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - ${PORT}:${PORT}
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: ./app/package.json
          target: /app/package.json
