# Generated by Django 4.2.1 on 2023-05-30 23:06

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('current', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('link', models.URLField(blank=True)),
                ('grade', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.education')),
            ],
            options={
                'ordering': ['education', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('S', 'Tool'), ('L', 'Language'), ('T', 'Technology')], max_length=1)),
                ('priority', models.IntegerField(blank=True, default=4)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['category', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.semester')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('current', models.BooleanField(default=False)),
                ('link_github', models.URLField(blank=True)),
                ('link_project', models.URLField(blank=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('current', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image')),
                ('link', models.URLField(blank=True)),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
            options={
                'ordering': ['-end_date', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='education',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='portfolio.subject'),
        ),
    ]
